version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/New_York
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: America/New_York
    labels:
      - dependencies
      - automation
    commit-message:
      prefix: "build(deps)"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: rust
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
