[application]
name = "g3-ui-playground"
default_platform = "web"
out_dir = "dist"


[web.app]
title = "g3_ui Playground"

[web.watcher]
reload_html = true
watch_path = ["src", "assets", "../src", "../assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
